'use strict';

module.exports = {
  SSDP_NT: 'http://www.thaliproject.org/ssdp',
  SSDP_ADVERTISEMENT_INTERVAL: 500,
  PEER_AVAILABILITY_WATCHER_INTERVAL: 1000,
  TCP_PEER_UNAVAILABILITY_THRESHOLD: 5 * 500,
  NON_TCP_PEER_UNAVAILABILITY_THRESHOLD: 30 * 1000,
  TCP_TIMEOUT_WIFI: 1000,
  TCP_TIMEOUT_BLUETOOTH: 5000,
  TCP_TIMEOUT_MPCF: 5000,
  NOTIFICATION_BEACON_PATH: '/NotificationBeacons',
  MAXIMUM_NATIVE_PEERS_CREATE_PEER_LISTENER_ADVERTISES: 20,
  MILLISECONDS_TO_WAIT_FOR_REVERSE_CONNECTION: 1000
};
