'use strict';

module.exports = {
  SSDP_NT: 'http://www.thaliproject.org/ssdp',
  SSDP_ADVERTISEMENT_INTERVAL: 500,
  PEER_AVAILABILITY_WATCHER_INTERVAL: 1000,
  TCP_TIMEOUT_WIFI: 1000,
  TCP_TIMEOUT_BLUETOOTH: 5000,
  TCP_TIMEOUT_MPCF: 5000
};
